export const arrayOfObjects = [
    {
        id: 1,
        count: 1,
        type: "text",
        display: "Begin in",
        sound: "sounds/begin-in-15-seconds.mp3",
    },
    {
        id: 2,
        count: 2,
        display: "15",
    },
    {
        id: 3,
        count: 3,
        display: "14",
    },
    {
        id: 4,
        count: 4,
        display: "13",
    },
    {
        id: 5,
        count: 5,
        display: "12",
    },
    {
        id: 6,
        count: 6,
        display: "11",
    },
    {
        id: 7,
        count: 7,
        display: "10",
    },
    {
        id: 8,
        count: 8,
        display: "9",
    },
    {
        id: 9,
        count: 9,
        display: "8",
    },
    {
        id: 10,
        count: 10,
        display: "7",
    },
    {
        id: 11,
        count: 11,
        display: "6",
    },
    {
        id: 12,
        count: 12,
        display: "5",
    },
    {
        id: 13,
        count: 13,
        display: "4",
    },
    {
        id: 14,
        count: 14,
        display: "3",
        sound: "sounds/3.mp3",
    },
    {
        id: 15,
        count: 15,
        display: "2",
        sound: "sounds/2.mp3",
    },
    {
        id: 16,
        count: 16,
        display: "1",
        sound: "sounds/1.mp3",
    },
    {
        id: 17,
        count: 17,
        display: "GO",
        sound: "sounds/go.mp3",
    },
    {
        id: 18,
        count: 18,
        display: "50",
    },
    {
        id: 19,
        count: 19,
        display: "49",
    },
    {
        id: 20,
        count: 20,
        display: "48",
    },
    {
        id: 21,
        count: 21,
        display: "47",
    },
    {
        id: 22,
        count: 22,
        display: "46",
    },
    {
        id: 23,
        count: 23,
        display: "45",
    },
    {
        id: 24,
        count: 24,
        display: "44",
    },
    {
        id: 25,
        count: 25,
        display: "43",
    },
    {
        id: 26,
        count: 26,
        display: "42",
    },
    {
        id: 27,
        count: 27,
        display: "41",
    },
    {
        id: 28,
        count: 28,
        display: "40",
    },
    {
        id: 29,
        count: 29,
        display: "39",
    },
    {
        id: 30,
        count: 30,
        display: "38",
    },
    {
        id: 31,
        count: 31,
        display: "37",
    },
    {
        id: 32,
        count: 32,
        display: "36",
    },
    {
        id: 33,
        count: 33,
        display: "35",
    },
    {
        id: 34,
        count: 34,
        display: "34",
    },
    {
        id: 35,
        count: 35,
        display: "33",
    },
    {
        id: 36,
        count: 36,
        display: "32",
    },
    {
        id: 37,
        count: 37,
        display: "31",
    },
    {
        id: 38,
        count: 38,
        display: "30",
    },
    {
        id: 39,
        count: 39,
        display: "29",
    },
    {
        id: 40,
        count: 40,
        display: "28",
    },
    {
        id: 41,
        count: 41,
        display: "27",
    },
    {
        id: 42,
        count: 42,
        display: "26",
    },
    {
        id: 43,
        count: 43,
        display: "25",
        sound: "sounds/25-seconds-left.mp3",
    },
    {
        id: 44,
        count: 44,
        display: "24",
    },
    {
        id: 45,
        count: 45,
        display: "23",
    },
    {
        id: 46,
        count: 46,
        display: "22",
    },
    {
        id: 47,
        count: 47,
        display: "21",
    },
    {
        id: 48,
        count: 48,
        display: "20",
    },
    {
        id: 49,
        count: 49,
        display: "19",
    },
    {
        id: 50,
        count: 50,
        display: "18",
    },
    {
        id: 51,
        count: 51,
        display: "17",
    },
    {
        id: 52,
        count: 52,
        display: "16",
    },
    {
        id: 53,
        count: 53,
        display: "15",
    },
    {
        id: 54,
        count: 54,
        display: "14",
    },
    {
        id: 55,
        count: 55,
        display: "13",
    },
    {
        id: 56,
        count: 56,
        display: "12",
    },
    {
        id: 57,
        count: 57,
        display: "11",
    },
    {
        id: 58,
        count: 58,
        display: "10",
    },
    {
        id: 59,
        count: 59,
        display: "9",
    },
    {
        id: 60,
        count: 60,
        display: "8",
    },
    {
        id: 61,
        count: 61,
        display: "7",
    },
    {
        id: 62,
        count: 62,
        display: "6",
    },
    {
        id: 63,
        count: 63,
        display: "5",
        sound: "sounds/5.mp3",
    },
    {
        id: 64,
        count: 64,
        display: "4",
        sound: "sounds/4.mp3",
    },
    {
        id: 65,
        count: 65,
        display: "3",
        sound: "sounds/3.mp3",
    },
    {
        id: 66,
        count: 66,
        display: "2",
        sound: "sounds/2.mp3",
    },
    {
        id: 67,
        count: 67,
        display: "1",
        sound: "sounds/1.mp3",
    },
    {
        id: 68,
        count: 68,
        type: "text",
        display: "Times up",
        sound: "sounds/times-up.mp3",
    },
];
